#!/usr/bin/env bash
# build

set -euo pipefail  # Fail immediately on any error
Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'

Prg=`head -1 go.mod | awk -F'/' '{print $NF}' | awk '{print $NF}'`
case "$OSTYPE" in
    "linux-gnu"* ) printf "==> Linux\n" && BINDIR=$GOPATH/bin && EXT="" ;;
    "darwin"* )    printf "==> macOS\n" && BINDIR=$GOPATH/bin && EXT="" ;;
    "msys"* )      printf "==> Windows with GitBASH\n" && BINDIR=$GOPATH/bin && EXT=".exe" ;;
    * )            printf "==> Unknown OS '$OSTYPE'. Aborting.\n" && exit 1 ;;
esac

printf "==> Update go.mod to reflect actual dependencies\ngo mod tidy\n"
go mod tidy
printf "\n==> Format Go code according to standard rules\ngo fmt ./...\n"
go fmt ./...
printf "\n==> Run tests for all packages in the repository\ngo test ./...\n"
go test ./...
printf "\n==> Install static analysis tool for Go\ngo install honnef.co/go/tools/cmd/staticcheck@latest\n"
go install honnef.co/go/tools/cmd/staticcheck@latest
printf "\n==> Analyze Go code for potential issues\nstaticcheck ./...\n"
staticcheck ./...

printf "\n==> Compile the maz package library: go build -o /dev/null ./pkg/maz\n"
go build -o /dev/null ./pkg/maz

# azm now has raf functionality via -sfn arg
# UTIL=raf
# printf "\n==> Build/install the ${Gre}$UTIL${Rst} utility\n"
# (
#   set -x  # Print commands as they execute
#   go build -o "${BINDIR}/${UTIL}${EXT}" -ldflags "-s -w" "./cmd/${UTIL}"
# )

UTIL=azm
printf "\n==> Build/install the ${Gre}$UTIL${Rst} utility\n"
(
  set -x
  go build -o "${BINDIR}/${UTIL}${EXT}" -ldflags "-s -w" "./cmd/${UTIL}"
)

# OPTIONAL: Examples to cross-compile for other OSes/archs:
# GOOS=darwin|linux|windows GOARCH=amd64|arm64 go build -ldflags "-s -w" -o ${BINDIR}/azm${EXT} 

# Additional processing for azm utility and overall repo maintenance
ProgramVersion=$(grep 'prgver.*=' cmd/azm/main.go || grep 'program_version.*=' cmd/azm/main.go | cut -d'"' -f2)
printf "\n==> azm program version = ${Gre}$ProgramVersion${Rst}\n"
printf "${Gre}$(ls -l ${BINDIR}/${UTIL}${EXT} | awk '{print sprintf("%'"'"'d", $5), $6, $7, $8, $9}')${Rst}\n"
printf "\n==> Warn on any 'replace' in go.mod\n${Red}$(grep replace go.mod)${Rst}\n"
printf "==> Last 5 tags = $(git tag | sort -V | tail -5 | tr '\n' ', ' | sed 's/,/  /g')\n"
CurrentTag=`git tag | sort -V | tail -1`
IFS='.' read -r Major Minor Patch <<< "${CurrentTag#v}"
NextTag="v$Major.$Minor.$((Patch+1))"
if [ "$ProgramVersion" != "${NextTag#v}" ]; then
    printf "==> Program version ${Gre}$ProgramVersion${Rst} and next tag ${Red}$NextTag${Rst} do NOT match!\n"
fi
printf "==> To release as ${Gre}$NextTag${Rst}, adjust comment and run below one-liner:\n"
printf "\n    TAG=${Gre}$NextTag${Rst} && git add . && git commit -m \"${Gre}<insert comment>${Rst}\" && git tag \$TAG && git push origin \$TAG && git push\n\n"

exit 0
